name: fair
description: Flutter Fair is a package used to update widget dynamically.
version: 2.5.0
homepage: https://fair.58.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

  fair_annotation: ^2.3.0
#  fair_annotation:
#    path: ../annotation

  fair_version: ^2.8.0
#  fair_version:
#    path: ../flutter_version/flutter_2_5_0
  flat_buffers: ^2.0.5
  url_launcher: ^6.0.10
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^2.3.0
  pedantic: ^1.11.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.wuba.fair
        pluginClass: FairPlugin
      ios:
        pluginClass: FairPlugin
  assets:
    - assets/
    - assets/fair_core/
    - assets/images/