name: fair_compiler
description: A complier which can generate Fair bundle for widget with annotation.
version: 0.3.0+1
homepage: https://fair.58.com/

environment:
  sdk: '>=2.7.0 <3.0.0'

#executables:
#  fairc:
dependencies:
  source_gen: ^0.9.4+5
  build: ^1.3.0
  crypto: ^2.0.0
  build_config: '>=0.2.6 <0.5.0'
  process: ^3.0.13
  archive: ^2.0.0
  intl: ^0.16.1
  path: ^1.6.4
  analyzer: ^0.41.2
  dart_style: ^1.3.6
  glob: ^1.2.0
  pedantic: ^1.8.0
#  fair_annotation: ^0.2.0
  fair_annotation:
    path: ../annotation
  http: ^0.12.2
  dartToJs:
    path: ../dart2js

dev_dependencies:
  test: ^1.6.0
