name: fair_dart2dsl
description: Companion compiler for fair_compiler for converting Dart to DSL.
version: 1.3.2
homepage: https://fair.58.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
executables:
  fairc:
dependencies:
  analyzer: ^5.5.0
  path: ^1.8.0
  args: ^2.3.0
  source_gen: ^1.2.2
  build: ^2.1.0

dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.1.2